import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import HomePage from '../components/guest/home'

const Home: NextPage = () => {
  return (
    <div className="bg-red-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
       <HomePage/>
      </main>

      <footer >
       
      </footer>
    </div>
  )
}

export default Home
